# Generated by Django 5.0.6 on 2024-07-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=64)),
                ('itemImage', models.URLField()),
                ('itemprice', models.CharField(max_length=10)),
            ],
        ),
    ]
