# Generated by Django 5.0.6 on 2024-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_image', models.URLField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_description', models.TextField()),
                ('item_type', models.CharField(max_length=32)),
            ],
        ),
    ]
