# Generated by Django 5.0.6 on 2024-07-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_bid_itemid_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemupdated',
            name='item_image',
            field=models.CharField(max_length=300),
        ),
    ]
